apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ggr-demo-accor
  labels:
    app: frontend
    tags.datadoghq.com/env: "ggr-demo-accor-260907"
    tags.datadoghq.com/service: "all-web"
    tags.datadoghq.com/version: "1.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        tags.datadoghq.com/env: "ggr-demo-accor-260907"
        tags.datadoghq.com/service: "all-web"
        tags.datadoghq.com/version: "1.0.0"
      annotations:
        ad.datadoghq.com/frontend.logs: '[{"source":"nginx","service":"all-web"}]'
    spec:
      containers:
        - name: frontend
          image: ggr-demo-accor/frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
