apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-api
  namespace: demo-accor
  labels:
    app: booking-api
    tags.datadoghq.com/env: "demo-accor-260907"
    tags.datadoghq.com/service: "booking-api"
    tags.datadoghq.com/version: "1.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-api
  template:
    metadata:
      labels:
        app: booking-api
        tags.datadoghq.com/env: "demo-accor-260907"
        tags.datadoghq.com/service: "booking-api"
        tags.datadoghq.com/version: "1.0.0"
      annotations:
        ad.datadoghq.com/booking-api.logs: '[{"source":"python","service":"booking-api"}]'
    spec:
      containers:
        - name: booking-api
          image: demo-accor/booking-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: DD_SERVICE
              value: "booking-api"
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_VERSION
              value: "1.0.0"
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_TRACE_PROPAGATION_STYLE
              value: "datadog,tracecontext"
            - name: PORT
              value: "8082"
            - name: DD_DBM_PROPAGATION_MODE
              value: "full"
            - name: PAYMENT_URL
              value: "http://payment-api:8083"
            - name: HOTEL_SEARCH_URL
              value: "http://hotel-search-api:8081"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: url
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 20
