apiVersion: v1
kind: Service
metadata:
  name: hotel-search-api
  namespace: demo-accor
  labels:
    app: hotel-search-api
spec:
  selector:
    app: hotel-search-api
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
