apiVersion: v1
kind: Service
metadata:
  name: payment-api
  namespace: demo-accor
  labels:
    app: payment-api
spec:
  selector:
    app: payment-api
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
